//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 08:05:29 PM GMT+03:00 
//


package by.it.meshchenko.jd02_09.TaskC;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.it.meshchenko.jd02_09.taskc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.it.meshchenko.jd02_09.taskc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShoppingCenters }
     * 
     */
    public ShoppingCenters createShoppingCenters() {
        return new ShoppingCenters();
    }

    /**
     * Create an instance of {@link ShoppingCenter }
     * 
     */
    public ShoppingCenter createShoppingCenter() {
        return new ShoppingCenter();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Room }
     * 
     */
    public Room createRoom() {
        return new Room();
    }

    /**
     * Create an instance of {@link Rooms }
     * 
     */
    public Rooms createRooms() {
        return new Rooms();
    }

}
