//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 11:32:56 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jd2_09.shelkovich.it.by", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.shelkovich.jd2_09;
