//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.25 at 12:15:19 AM EET 
//


package by.it.malyshev.jd02_09.generate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ancestor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Geocoord" type="{http://by/it/malyshev/jd02_09/generate}Geocoord"/>
 *         &lt;element name="Haplotype" type="{http://by/it/malyshev/jd02_09/generate}Haplotype"/>
 *       &lt;/sequence>
 *       &lt;attribute name="kit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person", propOrder = {
    "name",
    "ancestor",
    "country",
    "geocoord",
    "haplotype"
})
public class Person {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Ancestor", required = true)
    protected String ancestor;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "Geocoord", required = true)
    protected Geocoord geocoord;
    @XmlElement(name = "Haplotype", required = true)
    protected Haplotype haplotype;
    @XmlAttribute(name = "kit", required = true)
    protected String kit;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the ancestor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAncestor() {
        return ancestor;
    }

    /**
     * Sets the value of the ancestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAncestor(String value) {
        this.ancestor = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the geocoord property.
     * 
     * @return
     *     possible object is
     *     {@link Geocoord }
     *     
     */
    public Geocoord getGeocoord() {
        return geocoord;
    }

    /**
     * Sets the value of the geocoord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geocoord }
     *     
     */
    public void setGeocoord(Geocoord value) {
        this.geocoord = value;
    }

    /**
     * Gets the value of the haplotype property.
     * 
     * @return
     *     possible object is
     *     {@link Haplotype }
     *     
     */
    public Haplotype getHaplotype() {
        return haplotype;
    }

    /**
     * Sets the value of the haplotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Haplotype }
     *     
     */
    public void setHaplotype(Haplotype value) {
        this.haplotype = value;
    }

    /**
     * Gets the value of the kit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKit() {
        return kit;
    }

    /**
     * Sets the value of the kit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKit(String value) {
        this.kit = value;
    }

    @Override
    public String toString() {
        return "\n\tPerson{" +
                "\n\t\tKit='" + kit + '\'' +
                ", \n\t\tName='" + name + '\'' +
                ", \n\t\tAncestor='" + ancestor + '\'' +
                ", \n\t\tCountry='" + country + '\'' +
                ", \n\t\tGeocoord=" + geocoord +
                ", \n\t\tHaplotype=" + haplotype +
                '}';
    }

}
