//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.25 at 12:15:19 AM EET 
//


package by.it.malyshev.jd02_09.generate;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for STRmarkers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STRmarkers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DYS393" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS390" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS19" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS391" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS385a" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS385b" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS426" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS388" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS439" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS389i" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS392" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="DYS389ii" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STRmarkers", propOrder = {
    "dys393",
    "dys390",
    "dys19",
    "dys391",
    "dys385A",
    "dys385B",
    "dys426",
    "dys388",
    "dys439",
    "dys389I",
    "dys392",
    "dys389Ii"
})
public class STRmarkers {

    @XmlElement(name = "DYS393", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys393;
    @XmlElement(name = "DYS390", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys390;
    @XmlElement(name = "DYS19", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys19;
    @XmlElement(name = "DYS391", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys391;
    @XmlElement(name = "DYS385a", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys385A;
    @XmlElement(name = "DYS385b", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys385B;
    @XmlElement(name = "DYS426", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys426;
    @XmlElement(name = "DYS388", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys388;
    @XmlElement(name = "DYS439", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys439;
    @XmlElement(name = "DYS389i", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys389I;
    @XmlElement(name = "DYS392", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys392;
    @XmlElement(name = "DYS389ii", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dys389Ii;

    /**
     * Gets the value of the dys393 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS393() {
        return dys393;
    }

    /**
     * Sets the value of the dys393 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS393(BigInteger value) {
        this.dys393 = value;
    }

    /**
     * Gets the value of the dys390 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS390() {
        return dys390;
    }

    /**
     * Sets the value of the dys390 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS390(BigInteger value) {
        this.dys390 = value;
    }

    /**
     * Gets the value of the dys19 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS19() {
        return dys19;
    }

    /**
     * Sets the value of the dys19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS19(BigInteger value) {
        this.dys19 = value;
    }

    /**
     * Gets the value of the dys391 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS391() {
        return dys391;
    }

    /**
     * Sets the value of the dys391 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS391(BigInteger value) {
        this.dys391 = value;
    }

    /**
     * Gets the value of the dys385A property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS385A() {
        return dys385A;
    }

    /**
     * Sets the value of the dys385A property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS385A(BigInteger value) {
        this.dys385A = value;
    }

    /**
     * Gets the value of the dys385B property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS385B() {
        return dys385B;
    }

    /**
     * Sets the value of the dys385B property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS385B(BigInteger value) {
        this.dys385B = value;
    }

    /**
     * Gets the value of the dys426 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS426() {
        return dys426;
    }

    /**
     * Sets the value of the dys426 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS426(BigInteger value) {
        this.dys426 = value;
    }

    /**
     * Gets the value of the dys388 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS388() {
        return dys388;
    }

    /**
     * Sets the value of the dys388 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS388(BigInteger value) {
        this.dys388 = value;
    }

    /**
     * Gets the value of the dys439 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS439() {
        return dys439;
    }

    /**
     * Sets the value of the dys439 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS439(BigInteger value) {
        this.dys439 = value;
    }

    /**
     * Gets the value of the dys389I property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS389I() {
        return dys389I;
    }

    /**
     * Sets the value of the dys389I property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS389I(BigInteger value) {
        this.dys389I = value;
    }

    /**
     * Gets the value of the dys392 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS392() {
        return dys392;
    }

    /**
     * Sets the value of the dys392 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS392(BigInteger value) {
        this.dys392 = value;
    }

    /**
     * Gets the value of the dys389Ii property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDYS389Ii() {
        return dys389Ii;
    }

    /**
     * Sets the value of the dys389Ii property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDYS389Ii(BigInteger value) {
        this.dys389Ii = value;
    }

    @Override
    public String toString() {
        return "\n\t\t\t\t\tSTRmarkers{" +
                "\n\t\t\t\t\t\tDYS393=" + dys393 +
                ",\n\t\t\t\t\t\tDYS390=" + dys390 +
                ",\n\t\t\t\t\t\tDYS19=" + dys19 +
                ",\n\t\t\t\t\t\tDYS391=" + dys391 +
                ",\n\t\t\t\t\t\tDYS385a=" + dys385A +
                ",\n\t\t\t\t\t\tDYS385b=" + dys385B +
                ",\n\t\t\t\t\t\tDYS426=" + dys426 +
                ",\n\t\t\t\t\t\tDYS388=" + dys388 +
                ",\n\t\t\t\t\t\tDYS439=" + dys439 +
                ",\n\t\t\t\t\t\tDYS389i=" + dys389I +
                ",\n\t\t\t\t\t\tDYS392=" + dys392 +
                ",\n\t\t\t\t\t\tDYS389ii=" + dys389Ii +
                "}";
    }

}
